/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as RestockRouteImport } from './routes/restock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const RestockRoute = RestockRouteImport.update({
  id: '/restock',
  path: '/restock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecasts': typeof ForecastsRoute
  '/inventory': typeof InventoryRoute
  '/methodology': typeof MethodologyRoute
  '/restock': typeof RestockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecasts': typeof ForecastsRoute
  '/inventory': typeof InventoryRoute
  '/methodology': typeof MethodologyRoute
  '/restock': typeof RestockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecasts': typeof ForecastsRoute
  '/inventory': typeof InventoryRoute
  '/methodology': typeof MethodologyRoute
  '/restock': typeof RestockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forecasts' | '/inventory' | '/methodology' | '/restock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forecasts' | '/inventory' | '/methodology' | '/restock'
  id:
    '__root__' | '/' | '/forecasts' | '/inventory' | '/methodology' | '/restock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastsRoute: typeof ForecastsRoute
  InventoryRoute: typeof InventoryRoute
  MethodologyRoute: typeof MethodologyRoute
  RestockRoute: typeof RestockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restock': {
      id: '/restock'
      path: '/restock'
      fullPath: '/restock'
      preLoaderRoute: typeof RestockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastsRoute: ForecastsRoute,
  InventoryRoute: InventoryRoute,
  MethodologyRoute: MethodologyRoute,
  RestockRoute: RestockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
